### ISSUE TITLE
Something's wrong

### ISSUE THREAD

**Issue by Randore** [markgoodyear/headhesive.js#1]
I don't know what's wrong, I have picked up the code from demo but I'm getting this error.

ReferenceError: _mergeObj is not defined
file:///E:/copy/uxkraft/website/js/vendor/headhesive.js
Line 39

And one more thing, I would like to suggest if we use .header instead of .banner would be great because we are making header as sticky and not the banner.

**Comment by furays** [comment]
there's something went wrong with my menu after adding "headhesive-js-on-demand-sticky-header" as we can see on page http://reuncong.com/agrobisnis/bibit
all that i want is just like it shows in  demo but the dropdown and gelbutton item is disappear in original menu, the gelbutton is show up only in the clone when it's scroll-down without dropdown in it.  
I don't know how to combine among DynamicDrive's gooeymenu and DynamicDrive's ddlevelsmenu along with headhesive.min.js.
if i put a header-with-banner-class inside the DynamicDrive's ddlevelsmenu div, it also doesn't appear like in demo as i want it to be. As we can see on page http://reuncong.com/agrobisnis/kentang
could dearest Mark help me to figure it out, please...?
