### ISSUE TITLE
Specify a re-stick point (feature request)

### ISSUE THREAD

**Issue by 2xAA** [markgoodyear/headhesive.js#24]
I feel bad writing feature requests, but say you get to a certain point in the page and you need the unstuck element to stay there - like the top of a contact form so it doesn't get in the way.

**Comment by ghost** [comment]
Never be ashamed of making good requests. A developer cannot imagine every feature on his/her own. It is the end user that masters the tool that he see's other ways he would like it to work. With this type of feature request it is making Headhesive even better each month.

BTW, great idea.

Ciaran

**Comment by markgoodyear** [comment]
Just to add to what @cmwwebfx said — feature requests are encourage and appreciated no matter what it is.

In regards to this feature request, I like the idea, and it's something that could potentially be done through the callbacks with a custom function. I'll have a look at putting this together at some point for a demo.

**Comment by 2xAA** [comment]
Great, thanks both :)

**Comment by markgoodyear** [comment]
Here is a quick example of how you can do this using the `onInit()` callback:

``` js
onInit: function () {

  // Grab the cloned element.
  var elem = this.clonedElem;

  // Position to pause at.
  var pausePos = 900;

  // Listen for scroll.
  window.addEventListener('scroll', function () {

    // If greater or equal to the pause position.
    if (window.scrollY >= pausePos) {

      // Make sure there is no top already set, otherwise it'd keep adding to it.
      if (!elem.style.top) {

        // Set the styles to make it stick to the pause position.
        elem.style.position = 'absolute';
        elem.style.top = scrollY + 'px';
      }

    // If less than the pause position, remove styles to go back to normal.
    } else {
      elem.style.position = '';
      elem.style.top = '';
    }
  }, false);
}
```

I've tested this and it works pretty well. One thing you may need to do is change the styles so the transition is set to `transform` instead of `all`, otherwise it'll try animate the top property.

Any questions let me know!
