### ISSUE TITLE
Problems with TWBS mobile navigation

### ISSUE THREAD

**Issue by brubrant** [markgoodyear/headhesive.js#25]
If I use the default CSS I can't use the collapsed navigation as when I click on the button (not cloned) it triggers the cloned (hidden) collapsed-nav.

**Comment by brubrant** [comment]
In my case I fixed the problem with something like this:

```
$('.navbar-header button').click(function(event) {
    $('.navbar-collapse').not('.nav-clone .navbar-collapse').collapse('toggle');
});
```

**Comment by markgoodyear** [comment]
Marking as solved.
