### ISSUE TITLE
Button won't work with event handler after cloning

### ISSUE THREAD

**Issue by dave-green-uk** [markgoodyear/headhesive.js#26]
Hi @markgoodyear , love this plugin!

I'm using $('.menu-toggle').on('click' .....) to handle the opening of a navigation once a button is clicked. Once the header element containing the button has been cloned, however, the cloned button won't fire at all: even if I use a more specific selector containing **.headhesive**.

I've done a bit of reading and debugging but I keep coming back to the (perhaps incorrect) conclusion that the .on() method should be enough for this?

Do I need to register another event handler specifically for the cloned version of this button?

Any help greatly appreciated.

Cheers,
Dave

**Comment by dave-green-uk** [comment]
Closing as this is resolved by using a parent/ancestor element.

**Comment by markgoodyear** [comment]
Hey @davetgreen — Sorry it took me a while to reply to this. Glad you got it working! :smiley:
