### ISSUE TITLE
Getting an error when trying to implement headhesive

### ISSUE THREAD

**Issue by chanhman** [markgoodyear/headhesive.js#29]
Uncaught ReferenceError: _mergeObj is not defined

Trying to compare your demo file to mine and I can't seem to figure what else I need.

**Comment by markgoodyear** [comment]
@chanhman You're seeing this error as you're including the source file in your project, rather than the dist file. Make sure you use one of the files from the `dist` folder: https://github.com/markgoodyear/headhesive.js/tree/master/dist.
